---
title: "Graphiques avancés - étude de l'insuffisance rénale chronique (IRC)"
output: github_document
bibliography: biblio/references.bib
---

## Avant-propos

Vous devez avoir assimilé l'ensemble des notions du module quatre du cours de science des données biologiques 1 avant d'aborder ce projet. Il correspond au dépôt GitHub <https://github.com/BioDataScience-Course/A04Ia_graphe_avance>.

## Objectif

Ce projet est un projet **individuel**, **court** et **cadré**. L'objectif est de compléter votre apprentissage dans la visualisation des données. Il se focalise sur la réalisation et la description de différents types de graphiques :

-   des graphiques en barres
-   des boîtes de dispersion
-   des figures composées

## Consignes

Au sein du fichier `ckd_notebook.qmd`, réalisez et décrivez les différents graphiques demandés.

@rubini2015 et son équipe fournissent des informations complémentaires sur les données collectées (que l'on nomme métadonnées).

Effectuez un 'Rendu' du document final en HTML et assurez-vous que ce rendu se fait sans erreurs à la fin de votre travail (c'est très important, car c'est en effet ce document final que l'on souhaite obtenir en éditant un fichier Quarto) !

À la fin, vérifiez que le dernier commit est bien pris en compte dans votre dépôt sur GitHub. Nous ne voyons que la version GitHub et c'est cette dernière qui sera corrigée et évaluée. Il est donc crucial que vos dépôts locaux soient bien synchronisés avec GitHub à la fin de votre travail.

## Référence
