---
title: "Graphiques avancés"
author: "___"
date: "___"
output: html_document
---

```{r setup}
SciViews::R
```

<!--% Utilisez le code suivant pour importer les données dans la variable `ckd`. -->

<!--# Note: les patients du jeu de données initial pour lesquels il y avait des données manquantes dans les variables facteurs ont été supprimés ici. -->

```{r importation}
ckd <- read("../data/ckd.rds")
names(ckd)
```

<!--# La signification des variables et les unités sont expliquée ici: https://archive.ics.uci.edu/ml/datasets/Chronic_Kidney_Disease -->

<!--% Réalisez un dénombrement par classe (`class`) des patients présentant ou non une maladie de l'artère coronaire (`cad`) en utilisant de la couleur. Décrivez votre graphique en maximum 5 phrases. -->

```{r bar1}

```

<!--% Réalisez un dénombrement par classe (`class`) des patients présentant ou non des amas de cellules de pus (`pcc`) en utilisant de la couleur. Utilisez l'argument `position = "dodge"` Décrivez votre graphique en maximum 5 phrases. -->

```{r bar2}

```

<!--% Réalisez deux graphiques du dénombrement de l’hypertension (`htn`) en distinguant par la couleur les patients présentant un diabète sucré (`dm`). Utilisez un graphique en facettes pour la classe de patients (`class`). Pour le premier graphique, utiliser l'argument `position = "stack"` (option par défaut). Pour le second graphique, utiliser l'argument `position = "fill"`.
Décrivez vos graphiques en maximum 5 phrases. Que constatez-vous au niveau de l'axe des ordonnées ? -->

```{r bar3a}
# Avec position = "stack"

```

```{r bar3b}
# Avec position = "fill"

```

<!--% Réalisez un graphique en barres de la moyenne de la concentration en urée sanguine (`bu`) en fonction de la classe (`class`). Décrivez votre graphique en maximum 5 phrases. -->

```{r bar4}

```

<!--% Réalisez des boites de dispersion de la glycémie (`bgr`) en fonction de la classe (`class`). Décrivez-les en maximum 5 phrases. -->

```{r boxplot1}

```

<!--% Réalisez des boites de dispersion de la concentration en sodium (`sod`) en fonction de la classe (`class`) et de l'hypertension (`htn`) en couleur. Indiquez le nombre d'observation sur votre graphiques. Décrivez le en maximum 5 phrases. -->

```{r boxplot2}
give_n <- function(x)
  c(y = max(x) * 1.1, label = length(x)) 

```

<!--% Réalisez deux boites de dispersion, l'une représentant le nombre de globule blanc (`wc`) et l'autre le nombre de globule rouge (`rc`) en fonction de la classe (`class`). Ajoutez de la couleur en fonction de la classe. Assemblez ces deux graphiques sur une seule figure et décrivez-la en maximum 5 phrases. -->

```{r boxplot3composite}

```

<!--% Réalisez et commentez deux graphiques originaux (un graphique en barre et une boite de dispersion) à partir du jeu de données `ckd`. -->

```{r perso1}

```

```{r perso2}

```
